### ISSUE TITLE
App crashed on android, ok in IOS

### ISSUE THREAD

**Issue by fmsyscom** [mcongrove/com.mcongrove.slideMenu#6]
When i try to start the app in Android the app crash and send me that message:

```
[ERROR] :  MotionRecognitionManager: mSContextService = android.hardware.scontext.ISContextService$Stub$Proxy@1f07b2e
[ERROR] :  MotionRecognitionManager: motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@c80a6cf
[ERROR] :  MotionRecognitionManager: motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@c80a6cf
[ERROR] :  TiApplication: (main) [59,7503] Sending event: exception on thread: main msg:java.lang.NumberFormatException: Unable to convert null; Titanium 5.2.2,2016/03/28 14:12,b685ddb
[ERROR] :  TiApplication: java.lang.NumberFormatException: Unable to convert null
[ERROR] :  TiApplication:   at org.appcelerator.titanium.util.TiConvert.toInt(TiConvert.java:412)
[ERROR] :  TiApplication:   at ti.modules.titanium.ui.widget.tableview.TiTableView.<init>(TiTableView.java:356)
[ERROR] :  TiApplication:   at ti.modules.titanium.ui.widget.TiUITableView.processProperties(TiUITableView.java:111)
[ERROR] :  TiApplication:   at org.appcelerator.kroll.KrollProxy.setModelListener(KrollProxy.java:1219)
[ERROR] :  TiApplication:   at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:509)
[ERROR] :  TiApplication:   at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:500)
[ERROR] :  TiApplication:   at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:478)
[ERROR] :  TiApplication:   at ti.modules.titanium.ui.TableViewProxy.getTableView(TableViewProxy.java:152)
[ERROR] :  TiApplication:   at ti.modules.titanium.ui.TableViewProxy.handleAppendSection(TableViewProxy.java:319)
[ERROR] :  TiApplication:   at ti.modules.titanium.ui.TableViewProxy.handleMessage(TableViewProxy.java:923)
[ERROR] :  TiApplication:   at android.os.Handler.dispatchMessage(Handler.java:98)
[ERROR] :  TiApplication:   at android.os.Looper.loop(Looper.java:158)
[ERROR] :  TiApplication:   at android.app.ActivityThread.main(ActivityThread.java:7224)
[ERROR] :  TiApplication:   at java.lang.reflect.Method.invoke(Native Method)
[ERROR] :  TiApplication:   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
[ERROR] :  TiApplication:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
[ERROR] :  AndroidRuntime: FATAL EXCEPTION: main
[ERROR] :  AndroidRuntime: Process: net.myhealth, PID: 22860
[ERROR] :  AndroidRuntime: java.lang.NumberFormatException: Unable to convert null
[ERROR] :  AndroidRuntime:  at org.appcelerator.titanium.util.TiConvert.toInt(TiConvert.java:412)
[ERROR] :  AndroidRuntime:  at ti.modules.titanium.ui.widget.tableview.TiTableView.<init>(TiTableView.java:356)
[ERROR] :  AndroidRuntime:  at ti.modules.titanium.ui.widget.TiUITableView.processProperties(TiUITableView.java:111)
[ERROR] :  AndroidRuntime:  at org.appcelerator.kroll.KrollProxy.setModelListener(KrollProxy.java:1219)
[ERROR] :  AndroidRuntime:  at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:509)
[ERROR] :  AndroidRuntime:  at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:500)
[ERROR] :  AndroidRuntime:  at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:478)
[ERROR] :  AndroidRuntime:  at ti.modules.titanium.ui.TableViewProxy.getTableView(TableViewProxy.java:152)
[ERROR] :  AndroidRuntime:  at ti.modules.titanium.ui.TableViewProxy.handleAppendSection(TableViewProxy.java:319)
[ERROR] :  AndroidRuntime:  at ti.modules.titanium.ui.TableViewProxy.handleMessage(TableViewProxy.java:923)
[ERROR] :  AndroidRuntime:  at android.os.Handler.dispatchMessage(Handler.java:98)
[ERROR] :  AndroidRuntime:  at android.os.Looper.loop(Looper.java:158)
[ERROR] :  AndroidRuntime:  at android.app.ActivityThread.main(ActivityThread.java:7224)
[ERROR] :  AndroidRuntime:  at java.lang.reflect.Method.invoke(Native Method)
[ERROR] :  AndroidRuntime:  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
[ERROR] :  AndroidRuntime:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

why?

**Comment by Arwain76** [comment]
Get ready for this.... It was tough to find out but you simply have to change the TableView id's name to something else but Nodes. So into Widget.xml file, you have to write something like this:

`<TableView id="TBNodes" />`

And obviously you have to change it everywhere into widget.js (don't forget also to change the id in the addEventListener into your js).

Don't know why but Android doesn't like names like Nodes

Cheers

**Comment by Arwain76** [comment]
There was a reason because it doesn't like "Nodes"... into the plugin's tss there is:

`separatorStyle: Ti.UI.iPhone.TableViewSeparatorStyle.SINGLE_LINE`

move it into a platform specific rule and you're done :)

`"#Nodes[platform=ios]": {
    separatorStyle: Ti.UI.iPhone.TableViewSeparatorStyle.SINGLE_LINE
}`
